### PR TITLE
Update to the api-lib 1.*

### PR DESCRIPTION
**Pull request by wshafer**

### CODE REVIEW

**Comment by rodmcnew** [comment]
We reverted this. James said there is no 1.\* of api-lib.

**Comment by jerv13** [comment]
api-lib != user-api

**Comment by wshafer** [comment]
Oh...  api-lib does have a tag 1.0 and that one is using the correct packages.   the 0.* is still using depricated packages id reliv/rcm which is causing the core to be duplicated in the vendor folder.   This is the last package that is still by extension requesting the old package.

**Comment by rodmcnew** [comment]
https://packagist.org/packages/rcm/api-lib

**Pull request merged**
